# Generated by Django 5.0.14 on 2025-11-10 16:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'idempotency_keys',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('push', 'Push')], max_length=10)),
                ('user_id', models.UUIDField()),
                ('template_code', models.CharField(max_length=255)),
                ('variables', models.JSONField(default=dict)),
                ('request_id', models.CharField(max_length=255, unique=True)),
                ('priority', models.IntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['user_id'], name='notificatio_user_id_e78525_idx'), models.Index(fields=['request_id'], name='notificatio_request_d19539_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'), models.Index(fields=['status'], name='notificatio_status_fce6f5_idx')],
            },
        ),
    ]
